#!/bin/bash
# Load .env and construct DATABASE_URL
# This script is run by devcontainer postCreateCommand

set -e

ENV_FILE="/workspace/.env"

if [ ! -f "$ENV_FILE" ]; then
    echo "❌ Error: .env file not found at $ENV_FILE"
    exit 1
fi

# Load environment variables from .env
set -a
source "$ENV_FILE"
set +a

# Construct the URLs with actual values (expanded now, not at shell login)
DATABASE_URL="postgresql://${DB_USER_APP}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}?sslmode=disable"
SUPERUSER_DATABASE_URL="postgresql://${DB_USER_OWNER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}?sslmode=disable"

# Persist environment variables to shell with actual values (not variable references)
cat >> ~/.bashrc << EOF

# Auto-generated by setup-env.sh from .env
export DATABASE_URL="${DATABASE_URL}"
export SUPERUSER_DATABASE_URL="${SUPERUSER_DATABASE_URL}"
export DEVELOPMENT=true
EOF

echo "✅ Environment variables configured from .env"
echo "   DATABASE_URL: postgresql://${DB_USER_APP}:***@${DB_HOST}:${DB_PORT}/${DB_NAME}"
echo "   SUPERUSER_DATABASE_URL: postgresql://${DB_USER_OWNER}:***@${DB_HOST}:${DB_PORT}/${DB_NAME}"
