apiVersion: v1
kind: Service
metadata:
  name: postgres-development
spec:
  type: NodePort
  ports:
    - port: 5432
      targetPort: 5432
      nodePort: 30001
  selector:
    cnpg.io/cluster: nails-db-cluster
    role: primary
