apiVersion: nails-cli.dev/v1
kind: NailsApp
metadata:
  name: nails-app
  namespace: nails-demo
spec:
  replicas: 1
  version: 1.11.33
  primary_db_disk_size: 20
  keycloak_db_disk_size: 10

  # PgAdmin - Uncomment to install PgAdmin
  # pgadmin: true
  # Testing mode
  # testing: true

  # Used by the OAuth2 proxy and Keycloak (if installed) to configure redirects.
  hostname-url: https://localhost

  # Optional: lock component images by digest. If omitted, the operator uses `version` tags.
  # hash-app: sha256:2d25587aa3e2f99a67f6708c98b1a577fcecef29c48cd3053552c0e309b16b67
  # hash-app-pipeline: sha256:891c40ceda2ca6b23602692213d859fbae0b07fd3f93cca7d4a3881f9b7fe577
  # hash-app-db-migrations: sha256:b7a536aeb4c4e01aa6be1f7b8c7fe07b79b3389bc534180e9c4927fd16e52196
