name: Build Nails CLI

on:
  workflow_dispatch:
  push:
    paths:
      - 'crates/nails-cli/**'
  pull_request:
    paths:
      - 'crates/nails-cli/**'

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Earthly
        uses: earthly/actions/setup@v1
        with:
          version: v0.7.11

      - name: Earthly bootstrap
        run: earthly bootstrap

      - name: Run Earthly build
        run: earthly --ci --platform=linux/amd64 +nails-cli

      - name: List build output
        run: ls -lh ./nails
