name: Build Nails CLI Release

on:
  workflow_dispatch:
  release:
    types:
      - published

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Earthly
        uses: earthly/actions/setup@v1
        with:
          version: v0.7.11

      - name: Earthly bootstrap
        run: earthly bootstrap

      - name: Run Earthly build
        run: earthly --ci --platform=linux/amd64 +nails-cli

      - name: List build output
        run: ls -lh ./nails

      - name: Determine release tag
        id: release_tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [ "${{ github.event_name }}" = "release" ]; then
            tag="${{ github.event.release.tag_name }}"
          else
            tag=$(gh release list --limit 1 --json tagName --jq '.[0].tagName')
          fi

          if [ -z "$tag" ]; then
            echo "Unable to determine release tag" >&2
            exit 1
          fi

          echo "tag=$tag" >> "$GITHUB_OUTPUT"

      - name: Confirm crate version matches tag
        id: crate_version
        run: |
          tag="${{ steps.release_tag.outputs.tag }}"
          stripped_tag="${tag#v}"
          crate_version=$(cargo metadata --no-deps --format-version 1 --manifest-path crates/nails-cli/Cargo.toml | jq -r '.packages[0].version')

          if [ "$crate_version" != "$stripped_tag" ]; then
            echo "Crate version ($crate_version) does not match release tag ($tag)" >&2
            exit 1
          fi

          echo "version=$crate_version" >> "$GITHUB_OUTPUT"

      - name: Prepare release asset
        id: prepare_asset
        run: |
          tag="${{ steps.release_tag.outputs.tag }}"
          artifact_name="nails-cli-${tag}-x86_64-unknown-linux-gnu"
          cp ./nails "$artifact_name"
          echo "artifact_name=$artifact_name" >> "$GITHUB_OUTPUT"

      - name: Publish nails-cli crate
        if: github.event_name == 'release'
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: |
          if [ -z "$CARGO_REGISTRY_TOKEN" ]; then
            echo "CARGO_REGISTRY_TOKEN secret is required to publish" >&2
            exit 1
          fi

          cargo publish -p nails-cli --locked --token "$CARGO_REGISTRY_TOKEN"

      - name: Upload binary to release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload "${{ steps.release_tag.outputs.tag }}" "${{ steps.prepare_asset.outputs.artifact_name }}" --clobber
