name: Build Nails CLI

on:
  workflow_dispatch:
  push:
    paths:
      - 'crates/nails-cli/**'
  pull_request:
    paths:
      - 'crates/nails-cli/**'

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download latest earthly
        run: "sudo /bin/sh -c 'wget https://github.com/earthly/earthly/releases/latest/download/earthly-linux-amd64 -O /usr/local/bin/earthly && chmod +x /usr/local/bin/earthly'"

      - name: Earthly version
        run: earthly --version 

      - name: Run Earthly build
        run: earthly --ci --platform=linux/amd64 +nails-cli

      - name: List build output
        run: ls -lh ./nails
