name: Build Nails Operator Image

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'Image tag to publish (defaults to dev)'
        required: false
  release:
    types:
      - published

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      IMAGE_NAME: ghcr.io/nails/manager

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Earthly
        uses: earthly/actions/setup@v1
        with:
          version: v0.7.11

      - name: Earthly bootstrap
        run: earthly bootstrap

      - name: Resolve image tag
        id: tag
        run: |
          set -euo pipefail
          event_name="${{ github.event_name }}"

          if [ "$event_name" = "release" ]; then
            echo "value=${{ github.event.release.tag_name }}" >> "$GITHUB_OUTPUT"
            exit 0
          fi

          input_tag="${{ github.event.inputs.image_tag }}"
          if [ -n "$input_tag" ]; then
            echo "value=$input_tag" >> "$GITHUB_OUTPUT"
          else
            echo "value=dev" >> "$GITHUB_OUTPUT"
          fi

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push operator image
        env:
          IMAGE_TAG: ${{ steps.tag.outputs.value }}
        run: earthly --ci --push +nails-operator-image --IMAGE ${IMAGE_NAME}:${IMAGE_TAG}

      - name: Confirm published image
        run: echo "Published ${IMAGE_NAME}:${{ steps.tag.outputs.value }}"
